# Numpy Introduction, Array, List


In [2]:
# import numpy
import numpy as np

## 1. Array in NumPy  NumPy 中的数组
- Like list in Python an array is a data structure in NumPy. 与 Python 中的列表一样，数组是 NumPy 中的数据结构。
- An Array in NumPy can hold collection of ordered elements. NumPy 中的数组可以存储有序元素的集合。
- An array in NumPy can only hold data of same type. NumPy 中的数组只能存储相同类型的数据。
- You might occasionally hear an array being referred to as ‘ndarray’, which is shorthand for ‘N - dimensional array’. 你可能偶尔会听到数组被称为“ndarray”，这是“N 维数组”的缩写。
- An N - dimensional array is an array with n number of dimensions, for example 1-D or one dimensional array, 2-D or two dimensional array, and so on. 一个 N 维数组是一个具有 n 个维度的数组，例如 1-D 或一维数组、2-D 或二维数组，等等。

### a. Create NumPy Array from Python List 从 Python 列表创建 NumPy 数组

In [3]:
python_list = [1, 2, 3, 4, 5] # initialize a Python list
python_list # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [4]:
numpy_array1 = np.array(python_list)
numpy_array1 # Output: array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

### b. Compare Python List and NumPy Array 比较 Python 列表和 NumPy 数组
- Python List  Python 列表
    - Can contain data of different data types 可以包含不同数据类型的数据
    - Takes a huge amount of time and memory for numerical computations of large data 进行大型数据的数值计算需要大量时间和内存
- NumPy Array  NumPy 数组
    - Can contain data of same data type only 只能包含相同数据类型的数据
    - Very cheap in terms of time and memory for numerical computations of large data 对大型数据的数值计算在时间和内存方面非常高效

In [5]:
# Create two python List say 'List_x' and 'List_y'
X_list = list(range(100000))
Y_list = list(range(100000))

In [6]:
# Create two numpy array (say 'X' end 'Y') using above two list
X = np.array(X_list)
Y = np.array(Y_list)

In [7]:
# Define a function to calculate sum
# using python Lists X_list, Y_list)
def pure_python_version():
    Z = []
    for i in range(len(X_list)):
        Z.append(X_list[i] + Y_list[i])

In [8]:
# Define a function to calculate sum
# using numpy arrays (X, Y)
def numpy_version():
# In numpy we can directly perform
# sum element-wise as
    Z = X + Y

In [9]:
# Import Timer class from timeit Library
from timeit import Timer

# Create Timer objects for both functions
timer_obj1 = Timer("pure_python_version()",
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()",
                   "from __main__ import numpy_version")

print("Pure python version:",timer_obj1.timeit(1000))
print("Numpy version:",timer_obj2.timeit(1000))

Pure python version: 14.144548726966605
Numpy version: 0.0827546319924295


## 2. Attributes of an array and creating basic array 数组属性和创建基本数组

### a. Attributes of an Array  数组的属性
- The number of dimensions and items in an array is defined by its shape. 数组中的维度和项目数量由其形状定义。
- The dimensions are also called as axes. 维度也称为轴。
- Suppose, if you have a 2D array that looks like this: 假设你有一个如下所示的二维数组：
- [[1, 2, 3],
 [4, 5, 6]]
- In this case your array has two axes. First axis has length of two and the second axis has length of 3. See the image below: 在这种情况下，你的数组有两个轴。第一个轴的长度为 2，第二个轴的长度为 3。

### b. Shape, Size and Data Type of an Array 数组的形状、大小和数据类型

In [10]:
# Create a NumPy Array 创建一个 NumPy 数组
arr = np.array([[5,6,7], [8,9,10], [11,12,13], [1,2,3]])
arr

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

In [11]:
# Size of an Array 数组的大小
arr.size # Output: 12, Total number of elements in the array

12

In [12]:
# Data Types of Array 数组的类型
arr.dtype # Output: dtype('int64'), Data type of the elements in the array

dtype('int64')

In [13]:
# Shape of an Array 数组的形状
arr.shape # Output: (4, 3), Shape of the array, which means it has 4 rows and 3 columns

(4, 3)

In [14]:
# Dimension of an Array 数组的维度
arr.ndim # Output: 2, Number of dimensions in the array

2

In [17]:
# type() function and dtype method  type()函数和 dtype 方法
type(arr) # Output: <class 'numpy.ndarray'>, Type of the array

numpy.ndarray

In [16]:
arr.dtype # Output: dtype('int64'), Data type of the elements in the array

dtype('int64')

In [ ]:
# Caution: dtype method on Python Lists   注意：Python 列表的 dtype 方法
# Python List does not have dtype method

### c. Creating Basic NumPy Arrays 创建基本的 NumPy 数组

In [18]:
# array() function  array() 函数
# You can use the array() function to create a numpy array. 你可以使用 array()函数来创建一个 numpy 数组。
arr1 = np.array([[1, 2, 5, 7], [5, 2, 7, 6], [6, 2, 0, 8]])
arr1

array([[1, 2, 5, 7],
       [5, 2, 7, 6],
       [6, 2, 0, 8]])

In [25]:
# arange() function  arange() 函数
# Use arange() function to create collection of continuous integers.  使用 arange()函数来创建连续整数的集合。
arr2 = np.arange(10)
arr2 # Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), Creates an array of integers from 0 to 9

arr3 = np.arange(1, 10, 2) # start at 1, end at 10, step by 2
arr3
arr3.shape # Output: (5,), Shape of the array, which means it has 5 elements

(5,)

In [22]:
# zeros() function  zeros() 函数
# If you want to create a collection of zero values, you can use the zeros() function available in NumPy.  如果你想要创建一个包含零值的集合，可以使用 NumPy 中可用的 zeros()函数。

# The zeros() function creates an n-dimensional array of zeros. If no shape is specified, then it will create a one-dimensional array:  zeros()函数创建一个 n 维零数组。如果没有指定形状，它将创建一个一维数组：

arr4 = np.zeros(5) # Creates a one-dimensional array of zeros with 5 elements
arr4

array([0., 0., 0., 0., 0.])

In [23]:
# ones() function  ones() 函数
# In case you want collection of ones, NumPy has a function called ones().  如果你想要一个全 1 的集合，NumPy 有一个名为 ones()的函数。

arr5 = np.ones(4) # Creates a one-dimensional array of ones with 4 elements
arr5

array([1., 1., 1., 1.])

In [24]:
# linspace() function  linspace() 函数
# linspace() generates values which are equally spaced from each other.  linspace()生成彼此等距的值。

arr6 = np.linspace(1, 10, 5) # 第一位是起始，第二位是终止，第三位是生成的元素个数（如果不指定，则默认为 50）
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## 3. Exercise 练习

In [32]:
list1 = [2, 5, 8, 6, 4, 12, 16, 15]
# Create a NumPy array from the list1
exArray1 = np.array(list1)
exArray1.ndim

1

In [33]:
exArray2 = np.linspace(17, 31)
exArray2

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])