# Basic methods on array and reshaping 数组的基本操作和重塑

## 1. Add, Remove and Sort  添加、删除和排序

### a. Adding an Element  添加元素

In [1]:
import numpy as np

In [2]:
arr1 = np.array([2, 5, 7, 3, 4, 6])
arr1

array([2, 5, 7, 3, 4, 6])

In [3]:
# You can use append method to add an element in a NumPy array:  您可以使用 append 方法向 NumPy 数组中添加元素：
arr1 = np.append(arr1, 15)
arr1

array([ 2,  5,  7,  3,  4,  6, 15])

In [4]:
list1 = [2, 5, 4, 6, 7]
arr2 = np.append(list1, 10)
arr2

array([ 2,  5,  4,  6,  7, 10])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
arr1 = np.append(arr1, [11, 22])
arr1

array([ 2,  5,  7,  3,  4,  6, 15, 11, 22])

In [7]:
# Caution!  注意！
# A NumPy array doesn’t support append() method directly on the array. The given snippet will clear this:  NumPy 数组不能直接在数组上使用 append() 方法。下面的代码片段将说明这一点：
arr1.append(20)  # This will raise an error

AttributeError: 'numpy.ndarray' object has no attribute 'append'

### b. Removing an Element  删除元素

In [8]:
# You can remove an element from an array using delete method of NumPy. See the snippet below: 您可以使用 NumPy 的删除方法从数组中删除元素。

arr3 = np.array([2, 5, 7, 3, 4, 6])
arr3

array([2, 5, 7, 3, 4, 6])

In [34]:
np.delete(arr3, 2) # This will remove the element at index 2

array([2, 5, 3, 4, 6])

In [10]:
# You can also remove an element from a Python list using np.delete() method.  您也可以使用 np.delete()方法从 Python 列表中删除元素。
list2 = [2, 5, 4, 6, 7]
np.delete(list2, 2)  # This will remove the element at index 2

array([2, 5, 6, 7])

### c. Sorting an Array  排序数组

In [14]:
# You can quickly sort an array in ascending order as:   你可以快速将数组按升序排序
arr4 = np.array([2, 5, 7, 3, 4, 6])
np.sort(arr4)  # This will sort the array in ascending order

arr4.sort()  # This will sort the array in ascending order
arr4

array([2, 3, 4, 5, 6, 7])

## 2. Reshaping an Array  重塑数组
- Using np.reshape() will change the shape of your array.  使用 np.reshape() 会改变你的数组形状。
- Also, there won’t be any changes in the original data other than the shape.  此外，除了形状之外，原始数据不会发生任何变化。

In [26]:
# You can reshape an array using np.reshape() method.  您可以使用 np.reshape() 方法重塑数组。
arr5 = np.arange(0, 12)
np.reshape(arr5, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [28]:
arr5.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
# Using np.reshape() you can change the shape of a Python list but the returned object is of type numpy.ndarray, i.e., it becomes a NumPy array.  使用 np.reshape() 你可以改变 Python 列表的形状，但返回的对象是 numpy.ndarray 类型，即它变成了一个 NumPy 数组。
list3 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
np.reshape(list3, (2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### 3. Exercise 练习

In [30]:
exArray1 = np.arange(0, 16)
exArray1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

exArray2 = np.array(L)
exArray2 = np.sort(exArray2)
exArray2 = np.delete(exArray2, 4)
exArray2

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [54]:
L.append(53)
exArray3 = np.array(L)

exArray3 = np.reshape(exArray3, (2, 7))
exArray3

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])