# Basic methods on array and reshaping 数组的基本操作和重塑

## Add, Remove and Sort  添加、删除和排序

In [1]:
import numpy as np

In [2]:
arr1 = np.array([2, 5, 7, 3, 4, 6])
arr1

array([2, 5, 7, 3, 4, 6])

In [3]:
# You can use append method to add an element in a NumPy array:  您可以使用 append 方法向 NumPy 数组中添加元素：
arr1 = np.append(arr1, 15)
arr1

array([ 2,  5,  7,  3,  4,  6, 15])

In [4]:
list1 = [2, 5, 4, 6, 7]
arr2 = np.append(list1, 10)
arr2

array([ 2,  5,  4,  6,  7, 10])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
arr1 = np.append(arr1, [11, 22])
arr1

array([ 2,  5,  7,  3,  4,  6, 15, 11, 22])

In [7]:
# Caution!  注意！
# A NumPy array doesn’t support append() method directly on the array. The given snippet will clear this:  NumPy 数组不能直接在数组上使用 append() 方法。下面的代码片段将说明这一点：
arr1.append(20)  # This will raise an error

AttributeError: 'numpy.ndarray' object has no attribute 'append'