# Indexing and Slicing  索引和切片

## 1. Positive Indexing  正向索引

### a. Rows and Columns Indexes in an Array  数组中的行和列索引

In [1]:
# Conclusion: If you want to get the 4th element from an array, you should extract the element that is present at index 3.  结论：如果你想从数组中获取第 4 个元素，你应该提取索引为 3 处的元素。
import numpy as np

### b. Positive Single Indexing in an Array  数组中的正单索引

In [3]:
arr1 = np.array([10, 20, 30, 40])
arr1[2]

np.int64(30)

### c. Positive Single Indexing in Python Nested List  Python 嵌套列表的正单索引

In [4]:
# create a Python list
python_list1 = [[2, 4, 6], [8, 10, 12]]

python_list1[0][1]

4

### d. Positive Single Indexing in a NumPy Array   NumPy 数组中的正向单索引

In [5]:
num_arr = np.array(python_list1)
num_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
num_arr[0]

array([2, 4, 6])

In [7]:
num_arr[1][0]

np.int64(8)

### e. Positive Index Intervals in a NumPy Array   NumPy 数组中的正索引区间

In [8]:
# You can use semicolon (:) while indexing to get slices of elements from NumPy array.  您可以在索引时使用分号（:）来获取 NumPy 数组中的元素切片。

# In the snippet, num_arr[0, 0:2] will get you the row indexed at 0 and the columns indexed from 0 (inclusive) to 2 (exclusive).  在代码片段中，num_arr[0, 0:2] 将获取索引为 0 的行以及从索引 0（包含）到 2（不包含）的列。

# This is also known as slicing an array.  这也被称为数组切片。

num_arr[0, 0:2]  # get the first row and the first two columns

array([2, 4])

In [15]:
# You can slice rows and columns as shown in the snippet.  你可以像代码片段中那样切片行和列。

arr2 = np.arange(0, 16)
arr2 = arr2.reshape(4, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
arr2[1:3, 2:4]

array([[ 6,  7],
       [10, 11]])

## 2. Negative Indexing  负向索引

### a. Rows and Columns With Negative Indexes 带负索引的行和列

In [17]:
# Using Negative Single Index  使用负单索引
arr3 = np.arange(0, 6)
arr3

array([0, 1, 2, 3, 4, 5])

In [18]:
arr3[-3]

np.int64(3)

In [22]:
arr4 = np.arange(0, 9)
arr4 = arr4.reshape(3, 3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr4[-2]

array([3, 4, 5])

In [20]:
arr4[-2, -1]

np.int64(5)

### b. Negative Index Intervals  负索引区间

In [23]:
arr5 = np.arange(0, 16)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
arr5 = arr5.reshape(4, 4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
arr5[-3:-1, -2:]

array([[ 6,  7],
       [10, 11]])

## 3. Striding in Python  在 Python 中使用步长

In [38]:
arr6 = np.arange(0, 16)
arr6 = arr6.reshape(4, 4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
arr6[0:3:2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

## 4. Exercise  练习

In [41]:
exArray1 = np.arange(0, 25)
exArray1 = exArray1.reshape(5, 5)

exArray1[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [42]:
exArray1[1:6:2, 0:6:2]

array([[ 5,  7,  9],
       [15, 17, 19]])